cmd/status: Switch from bufio.Scanner to bufio.Reader
Closes #10

Some lines returned by TeamCity may be longer than the default bufio buffer allocation (64K). Rather than try to guess a maximum size for this buffer to avoid the bufio.ErrTooLong error, use `bufio.Reader` and its `ReadString()` to split up output per line instead.

Previously:

```console
$ tctest status 91578
Error: Error parsing test status response body: bufio.Scanner: token too long
Usage:
  tctest status # [flags]

Flags:
  -h, --help   help for status

Global Flags:
  -b, --buildtypeid string   the TeamCity BuildTypeId to trigger
      --fileregex string     the regex to filter files by` (default "(^[a-z]*/resource_|^[a-z]*/data_source_)")
  -p, --pass string          the TeamCity password to use (consider exporting pass to TCTEST_PASS instead)
  -r, --repo string          repository the pr resides in, such as terraform-providers/terraform-provider-azurerm
  -s, --server string        the TeamCity server's ur;
      --splittests string    split tests here and use the value on the left (default "_")
  -u, --user string          the TeamCity user to use

ERRO[2020-01-10 19:16:37] tctest: Error parsing test status response body: bufio.Scanner: token too long
```

Now:

```console
$ tctest status 91578
--- FAIL: TestAccAWSDBInstance_optionGroup (10.63s)
--- PASS: TestAccAWSDBInstance_namePrefix (457.41s)
--- SKIP: TestAccAWSDBInstance_ReplicateSourceDb_DeletionProtection (0.00s)
--- PASS: TestAccAWSDBInstance_basic (498.69s)
--- PASS: TestAccAWSDBInstance_IsAlreadyBeingDeleted (498.95s)
--- PASS: TestAccAWSDBInstance_iamAuth (517.00s)
--- PASS: TestAccAWSDBInstance_Password (520.89s)
--- PASS: TestAccAWSDBInstance_AllowMajorVersionUpgrade (554.09s)
--- PASS: TestAccAWSDBInstance_kmsKey (556.21s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier_SkipFinalSnapshot (578.77s)
--- PASS: TestAccAWSDBInstance_DeletionProtection (584.86s)
--- PASS: TestAccAWSDBInstance_generatedName (589.24s)
--- PASS: TestAccAWSDBInstance_MaxAllocatedStorage (600.65s)
--- PASS: TestAccAWSDBInstance_FinalSnapshotIdentifier (952.97s)
--- PASS: TestAccAWSDBInstance_subnetGroup (1004.38s)
--- FAIL: TestAccAWSDBInstance_S3Import (670.49s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AutoMinorVersionUpgrade (1336.47s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupWindow (1493.07s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb (1549.53s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllowMajorVersionUpgrade (1690.31s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AvailabilityZone (1691.29s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier (1239.61s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_IamDatabaseAuthenticationEnabled (1442.97s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaxAllocatedStorage (1442.85s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_AllocatedStorage (1983.22s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Monitoring (1505.80s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_BackupRetentionPeriod (2024.05s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_Port (1483.14s)
--- FAIL: TestAccAWSDBInstance_ReplicateSourceDb_VpcSecurityGroupIds (1485.07s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MaintenanceWindow (1584.03s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_ParameterGroupName (1654.91s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_CACertificateIdentifier (1685.52s)
--- SKIP: TestAccAWSDBInstance_SnapshotIdentifier_Tags_Unset (0.00s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AutoMinorVersionUpgrade (1118.83s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllocatedStorage (1542.91s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_MultiAZ (1997.81s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Io1Storage (1632.99s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AvailabilityZone (1219.58s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupWindow (1268.92s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod (1430.07s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaintenanceWindow (1097.78s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToDisabled (604.78s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_AllowMajorVersionUpgrade (2036.17s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_IamDatabaseAuthenticationEnabled (1410.45s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_DeletionProtection (1516.98s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_RemovedToEnabled (651.43s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_ParameterGroupName (1328.74s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MaxAllocatedStorage (1409.54s)
--- PASS: TestAccAWSDBInstance_MonitoringRoleArn_EnabledToRemoved (762.50s)
--- FAIL: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Oracle (2.73s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Tags (1227.94s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Monitoring (1432.85s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds (1190.27s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_Port (1379.40s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_BackupRetentionPeriod_Unset (1793.86s)
--- PASS: TestAccAWSDBInstance_portUpdate (516.64s)
--- PASS: TestAccAWSDBInstance_MonitoringInterval (1171.96s)
--- PASS: TestAccAWSDBInstance_separate_iops_update (729.08s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_VpcSecurityGroupIds_Tags (1313.00s)
--- PASS: TestAccAWSDBInstance_MinorVersion (411.85s)
--- PASS: TestAccAWSDBInstance_ec2Classic (439.09s)
--- PASS: TestAccAWSDBInstance_EnabledCloudwatchLogsExports_Postgresql (493.42s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfiguration (517.42s)
--- PASS: TestAccAWSDBInstance_cloudwatchLogsExportConfigurationUpdate (656.74s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ (2025.85s)
--- PASS: TestAccAWSRDSDBInstance_PerformanceInsightsEnabled_DisabledToEnabled (690.35s)
--- PASS: TestAccAWSRDSDBInstance_PerformanceInsightsRetentionPeriod (781.54s)
--- FAIL: TestAccAWSDBInstance_CACertificateIdentifier (615.83s)
--- PASS: TestAccAWSRDSDBInstance_PerformanceInsightsEnabled_EnabledToDisabled (891.73s)
--- PASS: TestAccAWSDBInstance_MSSQL_TZ (1451.74s)
--- PASS: TestAccAWSRDSDBInstance_PerformanceInsightsKmsKeyId (1038.84s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_PerformanceInsightsEnabled (1412.30s)
--- PASS: TestAccAWSDBInstance_ReplicateSourceDb_PerformanceInsightsEnabled (1584.18s)
--- PASS: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (1876.99s)
--- PASS: TestAccAWSDBInstance_SnapshotIdentifier_MultiAZ_SQLServer (4017.47s)
--- PASS: TestAccAWSDBInstance_MSSQL_Domain (3191.75s)
--- PASS: TestAccAWSDBInstance_MSSQL_DomainSnapshotRestore (3130.32s)
```